name = "Pulses"
uuid = "90cef440-570a-4d09-b559-6f8734d085b0"
authors = ["Alastair Marshall"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
